# Generated by Django 4.1.7 on 2023-03-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0003_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Withdraw",
        ),
    ]
