# Generated by Django 4.1.7 on 2023-03-15 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0005_rename_withdraw_contact"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Withdraw",
        ),
    ]
