# Generated by Django 4.1.7 on 2023-03-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currency", "0008_alter_contact_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="amount",
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="u_data",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
