# Generated by Django 4.1.7 on 2023-03-15 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0010_alter_category_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="category",
        ),
    ]
